services:
  db:
    image: postgres:16
    environment:
      POSTGRES_USER: xtracker
      POSTGRES_PASSWORD: xtracker
      POSTGRES_DB: xtracker
    ports:
      - "5432:5432"
    volumes:
      - dbdata:/var/lib/postgresql/data
volumes:
  dbdata:
